services:
  {{ cookiecutter.appName }}-prod:
    image: ghcr.io/{{ cookiecutter.owner }}/{{ cookiecutter.appName }}:prod
    container_name: {{ cookiecutter.appName }}-prod
    restart: unless-stopped

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080

    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ cookiecutter.appName }}-prod.rule=Host(`{{ cookiecutter.prodHost }}`) && PathPrefix(`{{ cookiecutter.routePrefix }}`)
      - traefik.http.routers.{{ cookiecutter.appName }}-prod.entrypoints=web,websecure
      - traefik.http.routers.{{ cookiecutter.appName }}-prod.tls=true
      - traefik.http.routers.{{ cookiecutter.appName }}-prod.tls.certresolver={{ cookiecutter.traefikCertResolver }}
      - traefik.http.middlewares.{{ cookiecutter.appName }}-prod-strip.stripprefix.prefixes={{ cookiecutter.routePrefix }}
      - traefik.http.routers.{{ cookiecutter.appName }}-prod.middlewares={{ cookiecutter.appName }}-prod-strip@docker
      - traefik.http.services.{{ cookiecutter.appName }}-prod.loadbalancer.server.port=8080

    networks:
      - {{ cookiecutter.dockerNetwork }}

networks:
  {{ cookiecutter.dockerNetwork }}:
    external: true
