services:
  {{ cookiecutter.appName }}-dev:
    image: ghcr.io/{{ cookiecutter.owner }}/{{ cookiecutter.appName }}:dev
    container_name: {{ cookiecutter.appName }}-dev
    restart: unless-stopped

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ cookiecutter.appName }}-dev.rule=Host(`{{ cookiecutter.devHost }}`) && PathPrefix(`{{ cookiecutter.routePrefix }}`)
      - traefik.http.routers.{{ cookiecutter.appName }}-dev.entrypoints=web,websecure
      - traefik.http.routers.{{ cookiecutter.appName }}-dev.tls=true
      - traefik.http.routers.{{ cookiecutter.appName }}-dev.tls.certresolver={{ cookiecutter.traefikCertResolver }}
      - traefik.http.middlewares.{{ cookiecutter.appName }}-dev-strip.stripprefix.prefixes={{ cookiecutter.routePrefix }}
      - traefik.http.routers.{{ cookiecutter.appName }}-dev.middlewares={{ cookiecutter.appName }}-dev-strip@docker
      - traefik.http.services.{{ cookiecutter.appName }}-dev.loadbalancer.server.port=8080

    networks:
      - {{ cookiecutter.dockerNetwork }}

networks:
  {{ cookiecutter.dockerNetwork }}:
    external: true
