services:
  {{ cookiecutter.appName }}-stage:
    image: ghcr.io/{{ cookiecutter.owner }}/{{ cookiecutter.appName }}:stage
    container_name: {{ cookiecutter.appName }}-stage
    restart: unless-stopped

    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ASPNETCORE_URLS: http://+:8080

    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ cookiecutter.appName }}-stage.rule=Host(`{{ cookiecutter.stageHost }}`) && PathPrefix(`{{ cookiecutter.routePrefix }}`)
      - traefik.http.routers.{{ cookiecutter.appName }}-stage.entrypoints=web,websecure
      - traefik.http.routers.{{ cookiecutter.appName }}-stage.tls=true
      - traefik.http.routers.{{ cookiecutter.appName }}-stage.tls.certresolver={{ cookiecutter.traefikCertResolver }}
      - traefik.http.middlewares.{{ cookiecutter.appName }}-stage-strip.stripprefix.prefixes={{ cookiecutter.routePrefix }}
      - traefik.http.routers.{{ cookiecutter.appName }}-stage.middlewares={{ cookiecutter.appName }}-stage-strip@docker
      - traefik.http.services.{{ cookiecutter.appName }}-stage.loadbalancer.server.port=8080

    networks:
      - {{ cookiecutter.dockerNetwork }}

networks:
  {{ cookiecutter.dockerNetwork }}:
    external: true
